### ISSUE TITLE
`All the Scans` module not working 

### ISSUE THREAD

**Issue by GiJ03** [Anteste/WebMap#2]
I am able to use the tool for individual scan modules like
 `1. Nmap` :white_check_mark:
 `2. Dirsearch` :white_check_mark:
 `3. Nikto` :white_check_mark:
 
 However, if I select `Option A: All the Scans`, I am getting the below error. :x:

:large_blue_diamond: **When tried with only google.com**
`Unable to init server: Could not connect: Connection refused
 Failed to parse arguments: Cannot open display:`

![image](https://user-images.githubusercontent.com/57536491/103474029-6dbe0d80-4dc5-11eb-88d8-340913338191.png)

:large_blue_diamond: **When tried with https://google.com**
`File "webmap.py", line 130, in <module>
    ipall = socket.gethostbyname(targetall)
socket.gaierror: [Errno -2] Name or service not known`

![image](https://user-images.githubusercontent.com/57536491/103474036-80d0dd80-4dc5-11eb-97dd-30cb9c1662d2.png)

**Comment by Anteste** [comment]
Have you installed the gnome terminal ?
`sudo apt-get install gnome-terminal`

**Comment by GiJ03** [comment]
Yes, I am already using the latest version of `gnome-terminal`. Still facing the issue mentioned above.

![image](https://user-images.githubusercontent.com/57536491/103569859-0c458e00-4eee-11eb-8fae-0f17fb20041a.png)

**Comment by GiJ03** [comment]
Please check the attach video for your reference.

https://user-images.githubusercontent.com/57536491/103570507-38adda00-4eef-11eb-85b2-d6626d5c4f13.mov

**Comment by Anteste** [comment]
HI GiJ03,
I looked for a fix to your issue and I found that was a common issue.
Sometimes gnome-terminal is laggy. 
Can you try to launch gnome-terminal ?
`$ sudo gnome-terminal`

If you have the same issue

### Fix 1
Try to reinstall gnome-terminal using the following commands
`$ sudo apt-get remove gnome-terminal`
`$ sudo apt-get purge gnome-terminal`
Then you can install it 
`$ sudo apt-get install gnome-terminal`

### Fix 2
You have to change this file /etc/ssh/sshd_config (with root permissions). Just add
`X11Forwarding yes`
After saving the file, initialize a new terminal or reboot the system.

### Fix 3
Try to run the following command on your terminal 
`$ export DISPLAY=:0.0`

**Comment by eburgueno** [comment]
The error `socket.gaierror: [Errno -2] Name or service not known` shouldn't have anything to do with the terminal, SSH, nor the display. It's typically the result of a network-level issue while attempting to resolve the provided hostname to an IP address.

@GiJ03 This can be quite hard to troubleshoot because no two networks behave the same, but the first thing I'd check is your `/etc/resolv.conf` to make sure all of your nameservers are working and can resolve domains just fine. To test them you can use `dig @<resolver IP> <address to resolve>` (eg: `dig @1.1.1.1 www.google.com`).

@Anteste it might be a good idea to enclose this particular call inside a try/except block, and maybe retry once before bailing out. You can catch it specifically with [`socket.gaierror`](https://docs.python.org/3/library/socket.html#socket.gaierror).

**Comment by GiJ03** [comment]
@eburgueno : Thanks! However, I am able to ping google.com. This means there is no issue with my `resolv.conf` right?

![image](https://user-images.githubusercontent.com/57536491/103686198-74f73e00-4fb4-11eb-9a7e-3d3a8a392da2.png)

**Comment by eburgueno** [comment]
@GiJ03 `ping` can be a good indicator of your local network health status. You probably want to leave it running in the background to make sure your `rtt` is consistent. As for `dig`, you need to check which nameservers are configured in your `/etc/resolv.conf` and use those instead of `@1.1.1.1`

**Comment by GiJ03** [comment]
@eburgueno : I have tried with the `nameserver` that is configured in my `resolv.conf` as well. Still the issue persists.

![image](https://user-images.githubusercontent.com/57536491/103732853-532aa500-500e-11eb-9c3a-f09d32bb7ee3.png)

**Comment by eburgueno** [comment]
@GiJ03 my apologies. I just re-read your report and I think I know what's going on, at least for the second issue you had (the `socket.gaierror: [Errno -2] Name or service not known` error). The problem is with the `https://` prefix:
```
$ dig @8.8.8.8 google.com|grep status
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47494
$ dig @8.8.8.8 https://google.com|grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41593
```
Similar behaviour with python's `socket.gethostbyname`:
```
$ python
Python 3.9.1 (default, Dec  8 2020, 00:00:00) 
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostbyname('google.com')
'142.250.67.14'
>>> socket.gethostbyname('https://google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```
Perhaps parsing user-provided URLs to extract the root domain could be a (separate) feature request :)

As for your original issue, please try the following:
```
# python
(...)
>>> import os
>>> os.system('gnome-terminal -- bash -c "echo it works! && bash"')
```
That should bring up a new gnome-terminal with the line "it works!" at the top, then a shell prompt.

**Comment by GiJ03** [comment]
@eburgueno : Thanks man! It worked now! We can close this issue now.
